### ISSUE TITLE
Open the popup menu using "modeler.get('elementTemplateChooser').open(element)" and click Select No response

### ISSUE THREAD

**Issue by zxiaozhou** [bpmn-io/element-template-chooser#21]
### Describe the Bug

1. Open the popup menu using modeler.get('elementTemplateChooser').open(element) and click Select No response
2. I want to add a button to my page to trigger the popup menu, but click the popup menu and choose nothing
<img width="774" alt="image" src="https://user-images.githubusercontent.com/62740686/222139858-cfbbd6ad-75da-49c4-9706-e90a1c5be90d.png">

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS] chrome 110
- OS: [e.g. Windows 7] mac 13.2.1 (22D68)
- Library version: [e.g. 2.0.0]   "bpmn-js": "^11.3.1",

**Comment by marstamm** [comment]
Hi @zxiaozhou ,

How can I reproduce this issue? Please add clear instructions on how to reproduce the issue so we can help you effectively. If possible, it would speed things up if you could provide a [CodeSandbox ](https://codesandbox.io/s/bpmn-js-starter-m3kex) that reproduces your problem.

Is it a problem with the library or do you need help integrating and expanding it in your own site? For general help and assistance, please open a thread in our [forum](https://forum.bpmn.io/).
