### ISSUE TITLE
When navigating a long list by the keyboard the list doesn't scroll

### ISSUE THREAD

**Issue by rpkoller** [bpmn-io/element-template-chooser#6]
__Describe the Bug__
For long lists https://github.com/bpmn-io/element-template-chooser/issues/3 has limited the height of the template chooser to prevent that the list extends below the fold. Problem is if you navigate the list by the cursor keys on the keyboard and you navigate down as soon as the last visible template is reached the focus disappears because the list doesn't scroll. 

__Steps to Reproduce__
1. open the template chooser (in case you have more templates available than the height of the template chooser)
2. hit the down key until the focus area disappears

__Expected Behavior__
the scroll position should mind the position of the focus area

__Environment__

- Host (Browser/Node version), if applicable: `Safari 13.1.2`, `Firefox 98.0.1`
- OS: `MacOS 10.13.6`
- Library version: `"@bpmn-io/element-template-chooser": "0.0.1"`

**Comment by rpkoller** [comment]
@barmac unfortunately i don't consider myself a developer therefor in regards of implementation, for javascript in particular, i am not much of a help. :/ i know html and css and am able to notice possible problematic parts but due to the fact not being a frontend dev  creating something on my own takes me a significant amount of time longer. i am more comfortable and savvy in the field of content strategy and additionally in ux and a11y.

**Comment by barmac** [comment]
That is fine. Thank you for getting back :)
